# Generated by Django 3.2.5 on 2021-11-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211121_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.author'),
        ),
    ]
