# Generated by Django 3.2.5 on 2021-11-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quotes_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
    ]
